name: Upload Python Package To Pypi

on:
  release:
    types: [published]

jobs:
  Pypi-Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: 构建 Python 包
      run: python -m build
    - name: 发布 Python 包至 Pypi
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
